# run me like
# snakemake --profile slurm -s ~/data/tools/rna_seq_standard_pipeline/workflow/Snakefile -p --use-conda --configfile config/config.yaml --latency-wait 50  --rerun-triggers mtime -n
samples: config/SraRunTable_fraction_rna.csv
star_index: /home/hayerk/data/index/GRCh38.p13/GENCODE_GRCh38.p13
salmon_index: /home/hayerk/data/index/gencode/gencode.v30.transcripts_salmon
blacklist: /home/hayerk/data/index/hg38-blacklist.v2.bed
gff3: /home/hayerk/data/index/GRCh38.p13/gencode.v32.primary_assembly.annotation.gff3
gtf: /home/hayerk/data/index/GRCh38.p13/gencode.v32.primary_assembly.annotation.gtf
tmp_dir: /scr1/users/hayerk/tmp
selected_genes: /mnt/isilon/thomas-tikhonenko_lab/data/index/selected_genes.bed
numbered_chr: /home/hayerk/data/index/hg38_only_numbered.bed
chrom_sizes: /home/hayerk/data/index/hg38_ad5.sizes
single_end: False
stranded: False
